version: 0.2
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - if [ ${CODEBUILD_WEBHOOK_TRIGGER} = "branch/main" ]; then IMAGE_TAG=latest; else IMAGE_TAG=${CODEBUILD_WEBHOOK_TRIGGER#tag/}; fi
  build:
    on-failure: ABORT
    commands:
      - docker build -t ${CUSTOM_METRICS_GENERATOR_REPOSITORY_URI}:${IMAGE_TAG} .
  post_build:
    on-failure: ABORT
    commands:
      - docker push ${CUSTOM_METRICS_GENERATOR_REPOSITORY_URI}:${IMAGE_TAG}
