apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-metrics-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-generator
rules:
  - apiGroups:
      - k8s.oder.com
    resources:
      - metricssources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.oder.com
    resources:
      - metricssources/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.oder.com
    resources:
      - metricssources/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-generator
subjects:
  - kind: ServiceAccount
    name: custom-metrics-generator
