# permissions for end users to view metricssources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricssource-viewer-role
rules:
- apiGroups:
  - k8s.oder.com
  resources:
  - metricssources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.oder.com
  resources:
  - metricssources/status
  verbs:
  - get
