# permissions for end users to edit metricssources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricssource-editor-role
rules:
- apiGroups:
  - k8s.oder.com
  resources:
  - metricssources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.oder.com
  resources:
  - metricssources/status
  verbs:
  - get
